### ISSUE TITLE
Syntax error while parsing AST from file running si bandit in Si workflow

### ISSUE THREAD

**Issue by pacospace** [thoth-station/si-bandit#39]
**Describe the bug**
syntax error while parsing AST from file running si bandit in Si workflow

**To Reproduce**
1. Use same inputs to schedule si workflow

**Expected behavior**

**Screenshots**
```
Name:                security-indicator-81d8e006
Namespace:           thoth-middletier-stage
ServiceAccount:      argo
Status:              Failed
Conditions:          
 Completed           True
Created:             Fri Oct 02 14:17:56 +0200 (1 hour ago)
Started:             Fri Oct 02 16:03:40 +0200 (1 minute ago)
Finished:            Fri Oct 02 16:05:35 +0200 (now)
Duration:            1 minute 55 seconds
ResourcesDuration:   2m8s*(1 cpu),7m30s*(100Mi memory)
Parameters:          
  ceph_bucket_prefix: data
  ceph_bucket_name:  thoth
  ceph_host:         s3.upshift.redhat.com
  deployment_name:   ocp-stage
  THOTH_SECURITY_INDICATORS_JOB_ID: security-indicator-81d8e006
  THOTH_DOCUMENT_ID: security-indicator-81d8e006
  THOTH_SECURITY_INDICATORS_PACKAGE_NAME: rb
  THOTH_SECURITY_INDICATORS_PACKAGE_VERSION: 0.9.2
  THOTH_SECURITY_INDICATORS_PACKAGE_INDEX: https://pypi.org/simple
  THOTH_SECURITY_INDICATORS_AGGREGATION_FUNCTION: process_data
  THOTH_FORCE_SYNC:  0

STEP                                   TEMPLATE                           PODNAME                                 DURATION  MESSAGE
 ✖ security-indicator-81d8e006         security-indicators                                                                                           
 ├-✔ download-package                  download-package/download-package  security-indicator-81d8e006-3716313097  47s                                
 ├-✖ bandit                            bandit/bandit-from-dir             security-indicator-81d8e006-562169286   1m        failed with exit code 1  
 ├-✔ cloc                              cloc/cloc-from-dir                 security-indicator-81d8e006-4047535669  30s                                
                                                                                                                                                              
 ✔ security-indicator-81d8e006.onExit  exit-handler                                                                                                  
 └---✔ delete-pvc                      delete-pvc                         security-indicator-81d8e006-2304673912  4s          

```                       

```
 fmurdaca@pc-7  ~  argo logs security-indicator-81d8e006
security-indicator-81d8e006-3716313097: 2020-10-02T14:04:16.241652688Z {"name": "thoth.common", "levelname": "WARNING", "module": "logging", "lineno": 344, "funcname": "init_logging", "created": 1601647456.2411687, "asctime": "2020-10-02 14:04:16,241", "msecs": 241.16873741149902, "relative_created": 7696.843147277832, "process": 1, "message": "Logging to a Sentry instance is turned off"}
security-indicator-81d8e006-4047535669: 2020-10-02T14:04:48.918811435Z 2020-10-02 14:04:48,918   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-81d8e006-4047535669: 2020-10-02T14:04:48.918811435Z 2020-10-02 14:04:48,918   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-81d8e006-4047535669: 2020-10-02T14:04:48.919029207Z 2020-10-02 14:04:48,918   1 INFO     si-cloc:39: SI Cloc v0.1.3+analyzer.0.1.8.common.0.19.0.
security-indicator-81d8e006-4047535669: 2020-10-02T14:04:55.722588235Z 2020-10-02 14:04:55,722   1 INFO     thoth.analyzer.cli:175: Writing results to '/mnt/workdir/cloc_results'
security-indicator-81d8e006-562169286: 2020-10-02T14:05:21.991104518Z 2020-10-02 14:05:21,990   1 WARNING  thoth.common:346: Logging to a Sentry instance is turned off
security-indicator-81d8e006-562169286: 2020-10-02T14:05:21.991313796Z 2020-10-02 14:05:21,991   1 INFO     thoth.common:368: Logging to rsyslog endpoint is turned off
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 829, in __call__
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     out = _run_bandit(from_directory)
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "app.py", line 124, in si_bandit
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "app.py", line 59, in _run_bandit
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     raise Exception(out["errors"])
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z 2020-10-02 14:05:25,994   1 CRITICAL root:102: Traceback (most recent call last):
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "app.py", line 150, in <module>
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     __name__ == "__main__" and si_bandit()
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z Exception: [{'filename': '/mnt/workdir/package/rb-0.9.2/rb/_rediscommands.py', 'reason': 'syntax error while parsing AST from file'}]
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     return self.main(*args, **kwargs)
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 782, in main
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     rv = self.invoke(ctx)
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     return ctx.invoke(self.callback, **ctx.params)
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "/opt/app-root/lib/python3.6/site-packages/click/core.py", line 610, in invoke
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     return callback(*args, **kwargs)
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z   File "/opt/app-root/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z     return f(get_current_context(), *args, **kwargs)
security-indicator-81d8e006-562169286: 2020-10-02T14:05:25.99445356Z 
security-indicator-81d8e006-2304673912: 2020-10-02T14:05:33.1082899Z time="2020-10-02T14:05:33.104Z" level=info msg="Starting Workflow Executor" version=v2.11.0
security-indicator-81d8e006-2304673912: 2020-10-02T14:05:33.193182457Z time="2020-10-02T14:05:33.193Z" level=info msg="Executor (version: v2.11.0, build_date: 2020-09-17T22:51:06Z) initialized (pod: thoth-middletier-stage/security-indicator-81d8e006-2304673912) with template:\n{\"name\":\"delete-pvc\",\"arguments\":{},\"inputs\":{},\"outputs\":{},\"metadata\":{},\"resource\":{\"action\":\"delete\",\"manifest\":\"apiVersion: v1\\nkind: PersistentVolumeClaim\\nmetadata:\\n  name: security-indicator-81d8e006-workdir\\n\"}}"
security-indicator-81d8e006-2304673912: 2020-10-02T14:05:33.193182457Z time="2020-10-02T14:05:33.193Z" level=info msg="Creating a K8sAPI executor"
security-indicator-81d8e006-2304673912: 2020-10-02T14:05:33.193229524Z time="2020-10-02T14:05:33.193Z" level=info msg="Loading manifest to /tmp/manifest.yaml"
security-indicator-81d8e006-2304673912: 2020-10-02T14:05:33.193688054Z time="2020-10-02T14:05:33.193Z" level=info msg="kubectl delete --ignore-not-found -f /tmp/manifest.yaml -o name"

```

**Additional context**

**Comment by KPostOffice** [comment]
I'm thinking this is probably because rb-0.9.2 is python2 only

**Comment by KPostOffice** [comment]
We need to use the python2.7 version of bandit when gathering SI

**Comment by goern** [comment]
can we exclude py2 packages and generate a general justification to migrate to py3? 

@fridex

**Comment by fridex** [comment]
We already exclude packages that are not installable to py2 environments. We provide a generic "the given package is not installable into the given runtime environment" justification. With error classification in place, we can also provide info about lacking py3 support for these packages.

**Comment by pacospace** [comment]
> I'm thinking this is probably because rb-0.9.2 is python2 only

I saw more errors like this and more (others might be different) and this is slowing down knowledge acquisition as we continosly reschedule these SI analysis for packages that are going to fail. As we did for packages that do not provide distro, we should do something similar for these kind of errors so that Thoth can learn about them and do not schedule them again.

Maybe we should do the same as we do for solver errors and introduce not analyzable for si-bandit or si-cloc?  Also collecting the errors we can see what kind of errors are present and maybe open issues on bandit project?

for packages that do not provide distro you can see that it's not so small percentage:
![Screenshot from 2020-10-05 09-17-12](https://user-images.githubusercontent.com/27498679/95050313-9c0b4e80-06eb-11eb-9685-f432f76b1b0b.png)

@fridex @goern @KPostOffice

**Comment by fridex** [comment]
You can follow the same pattern as for solver - solver states that a package is unsolvable in the resulting JSON (instead of failing unrecoverably). The syncing part of the SI graph-sync would propagate this fact to the database as a flag.

**Comment by fridex** [comment]
> You can follow the same pattern as for solver - solver states that a package is unsolvable in the resulting JSON (instead of failing unrecoverably). The syncing part of the SI graph-sync would propagate this fact to the database as a flag.

And this can be done for all the tasks - si-bandit, si-cloc and any other introduced in the system.

**Comment by pacospace** [comment]
Opened this feature: https://github.com/thoth-station/thoth-application/issues/538.

**Comment by KPostOffice** [comment]
Errors should persist in the DB now
